# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Simon Turner | Blog
email: simonturner34@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for things that I make
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true

sass:
  sass_dir: _sass

texture:
  title: Simon Turner
  tagline: A place for things that I make
  date_format: "%b %-d, %Y"
  style: purple
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: morphashark
    github:  nocturnaltortoise
    instagram:  morphashark
    rss: rss

# Build settings
markdown: kramdown
# theme: minima
remote_theme: thelehhman/texture
exclude:
  - Gemfile
  - Gemfile.lock

plugins_dir:
  - jekyll-seo-tag
